# Generated by Django 4.0.5 on 2022-06-19 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, unique=True, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Tecnico Juridico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caratulado', models.CharField(max_length=200, verbose_name='Caratulado de la causa')),
                ('rol', models.CharField(max_length=100, verbose_name='Rol de la causa')),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(max_length=100, verbose_name='Estado de la causa')),
                ('abogados', models.ManyToManyField(to='core.abogado')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, unique=True, verbose_name='Rut')),
                ('p_nombre', models.CharField(max_length=15, verbose_name='Primer Nombre')),
                ('s_nombre', models.CharField(max_length=15, verbose_name='Segundo Nombre')),
                ('ap_paterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre de la Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(null=True, verbose_name='Valor total del contato')),
                ('archivo_contrato', models.FileField(upload_to='', verbose_name='Archivo del contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la corte')),
            ],
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor de la cuota')),
                ('fecha_pago', models.DateField(null=True, verbose_name='Fecha de Pago de la Cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento de la cuota')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(verbose_name='Se encuentra o no pagada la cuota')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrato')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuotas')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15, verbose_name='Estado Civil')),
            ],
        ),
        migrations.CreateModel(
            name='Estadocontrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15, verbose_name='Estado Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Nombre de la Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre de la Region')),
            ],
        ),
        migrations.CreateModel(
            name='TecnicoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, unique=True, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Tecnico Juridico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(verbose_name='Folio del presente tramite')),
                ('foja', models.IntegerField(verbose_name='Foja en el archivador')),
                ('documento', models.FileField(blank=True, upload_to='', verbose_name='Copia del archivo encontrado en la pagina del poder judicial')),
                ('etapa', models.CharField(max_length=200, verbose_name='Etapa en la que fue introducido')),
                ('descripcion_tramite', models.TextField()),
                ('fecha_tramite', models.DateField(verbose_name='Fecha del tramite')),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.causa')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del tribunal')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corte')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='cuotas',
            name='contrato',
            field=models.ManyToManyField(through='core.DetalleCuotas', to='core.contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tecnico_juridico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecnicojuridico', verbose_name='Tecnico a cargo del contrato'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadocivil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nacionalidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='causa',
            name='clientes',
            field=models.ManyToManyField(to='core.cliente'),
        ),
        migrations.AddField(
            model_name='causa',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrato'),
        ),
        migrations.AddField(
            model_name='causa',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tribunal'),
        ),
    ]
