# Generated by Django 4.0.5 on 2022-06-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_abogado_causa_cliente_comuna_contrato_corte_cuotas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_estado_civil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_nacionalidad',
        ),
    ]
