# Generated by Django 4.0.5 on 2022-06-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cliente_id_comuna_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='id_region',
            new_name='region',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estadocivil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.nacionalidad'),
            preserve_default=False,
        ),
    ]
