# Generated by Django 4.0.5 on 2022-06-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_region_comuna_region_cliente_comuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nacionalidad',
        ),
    ]
