# Generated by Django 4.0.5 on 2022-06-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cliente_comuna_remove_cliente_estado_civil_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
