# Generated by Django 4.0.5 on 2022-06-21 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_remove_abogado_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_solicitud', models.CharField(max_length=200, verbose_name='Resumen de la solicitud, maximo 200 caracteres')),
                ('solicitud', models.TextField(verbose_name='Describa con mayor detalle la solicitud')),
                ('fecha_solicitud', models.DateField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
