# Generated by Django 4.0.5 on 2022-06-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_contrato_tecnico_juridico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nombre_contrato',
            field=models.CharField(max_length=100, verbose_name='Nombre del tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.IntegerField(blank=True, default=0, verbose_name='Valor total del contato'),
            preserve_default=False,
        ),
    ]
