# Generated by Django 4.0.5 on 2022-06-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contrato_nombre_contrato_alter_contrato_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo_contrato',
            field=models.FileField(null=True, upload_to='', verbose_name='Archivo del contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.IntegerField(null=True, verbose_name='Valor total del contato'),
        ),
    ]
