# Generated by Django 4.0.5 on 2022-06-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_contrato_archivo_contrato_alter_contrato_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo_contrato',
            field=models.FileField(blank=True, upload_to='', verbose_name='Archivo del contrato'),
        ),
    ]
