# Generated by Django 4.0.5 on 2022-06-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_estadopresupuesto_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopresupuesto',
            name='Descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
