# Generated by Django 4.0.5 on 2022-06-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_estadopresupuesto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopresupuesto',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
