# Generated by Django 4.0.5 on 2022-06-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_descripcion_estadopresupuesto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.estadopresupuesto'),
        ),
    ]
