# Generated by Django 4.0.5 on 2022-06-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_presupuesto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cuotas_contrato',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecuotas',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Se encuentra o no pagada la cuota'),
        ),
    ]
